version: 2.1
orbs:
  # orgs contain basic recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  deploy:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.15"
    steps:
      # install node and checkout code and setup needed for aws, node, elastic beanstalk
      - node/install
      - checkout
      - eb/setup
      - aws-cli/setup
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Checking Versions
          command: |
            node --version
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      # TODO: Install dependencies in the the backend API          
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      # TODO: Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
      # TODO: Build the frontend app
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # TODO: Build the backend API      
      - run:
          name: API Build
          command: |
            npm run api:build
      # TODO: Deploy the backend API & frontend      
      - run:
          name: Deploy App
          command: |
            npm run deploy          
workflows:
  udagram:
    jobs:
      - deploy
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - deploy
